=== ctllin/commonUtils/src/main/java/com/ctl/utils/xml/validate/email.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/email" xmlns:tns="http://www.example.org/email" elementFormDefault="qualified">
	<element name="email">
		<complexType>
			<sequence>
				<element name="from" type="string"/>
				<element name="to" type="string"/>
				<element name="subject" type="string"/>
				<element name="body" type="string"/>
				<element name="student">
				   	<complexType>
		        	<sequence>
		       				<element name="id" type="string"/>
							<element name="name" type="string"/>
		       	  </sequence>
		       	</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== ctllin/commonUtils/src/main/resources/email.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:email xmlns:tns="http://www.example.org/email" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/email email.xsd ">
  <tns:from>赵敏</tns:from>
  <tns:to>张无忌</tns:to>
  <tns:subject>say hello</tns:subject>
  <tns:body>周五下午开会!</tns:body>
  <tns:student>
      <tns:id>i</tns:id>	
      <tns:name>name</tns:name>
  </tns:student>
</tns:email>
